name: Deploy Bot

on:
  push:
    branches: [ main ]  # Make sure your branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 18.188.26.233
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure this secret exists
          script: |
            cd BMM-VPS
            git pull origin main
            npm install
            pm2 restart techitoon-bot || pm2 start src/index.js --name techitoon-bot
